### ISSUE TITLE
Testa att mata in olika tecken , många tecken och lämna fält tomma i registreringen.

### ISSUE THREAD

**Issue by joelgille** [joelgille/Grupp5#3]
Resultat:
-Edge och Google Chrome (dator) - Funkar buggfritt
Samsung internet (android): funkar buggfritt men ej som förväntat. Det var svårare att hitta halv dold knapp.
-Safari (iphone) - funkar buggfritt men ej som förväntat. Det var svårare att hitta halv dold knapp

**Comment by michelafram** [comment]
toppen :)

**Comment by EkaterinaFomenko** [comment]
Hej Joel ) Har du märkt att om man registrerar sig som en företagsanvändare (!) finns det i formulären frågor om personalnummer, förnamn och efternamn. Det tycker jag är konstiga uppgifterna för företag. Jag tror att det är ett fel. Det vore bättre och logiskt också att få välja konto typ (företag eller privat användare) i början av formulären. Vad sägs? :)

**Comment by joelgille** [comment]
Ja kanske , får kika på det!

Den 17 sep. 2017 21:04 skrev "EkaterinaFomenko" <notifications@github.com>:

**Comment by EkaterinaFomenko** [comment]
I registreringsformulären står det att Användarnamn endast får innehålla  bokstäver (utan undantag), siffror och bindestreck, Men jag kan inte registrera ett namn med bokstäverna Ä, Ö och Å. Det är inte bra ) 

Ska jag skriva det här eller i Whatsapp?

**Comment by joelgille** [comment]
Gör det

Den 17 sep. 2017 21:38 skrev "EkaterinaFomenko" <notifications@github.com>:

**Comment by Tanjina26** [comment]
Resultat:

-Edge och Google Chrome (dator) - Funkar buggfritt

-Samsung internet (android): funkar buggfritt men ej som förväntat.  Det var svårare att hitta halv dold knapp.

-Safari (iphone) - funkar buggfritt men ej som förväntat.  Det var svårare att hitta halv dold knapp
