### ISSUE TITLE
Testa att ta bort en auktion innan och efter den publicerats.

### ISSUE THREAD

**Issue by joelgille** [joelgille/Grupp5#31]
Resultat:
-Edge och Google Chrome (dator) - Funkar innan publicering (inte efter).
-Saumsung internet (android) - Funkar innan publicering (inte efter).
-Safari - Funkar innan publicering (inte efter).

**Comment by Tanjina26** [comment]
-safari -funkar innan publicering (inte efter).

**Comment by Tanjina26** [comment]
resultat:

Att ta bort Innan publicering - funkar buggfritt.

Att ta bort efter publicering - Bug i alla webbläsare.  Det går inte att ta bort auktionen.
